### ISSUE TITLE
Transition plan

### ISSUE THREAD

**Issue by krassowski** [python-lsp/python-lsp-server#4]
Items based on @ccordoba12's https://github.com/palantir/python-language-server/pull/901#issuecomment-771180214:
- [x] move this repo under `python-lsp/python-lsp-server`
- [x] rename the package to `python-lsp-server` (#10)
- [x] remove versioneer (#10)
- [x] rewrite the Readme to remove references to VSCode (its client hasn't received any update in ages) (#11)
- [x] get a new version on PyPI.
- [x] Release a new version of python-lsp-jsonrpc (https://github.com/python-lsp/python-lsp-jsonrpc/pull/2).

My wishlist:
- [x] rewrite the readme to markdown (#6)
- [x] remove Python 2 support (#10)
- [x] update copyrights notices; the last commit under Palantir was in December 2020, so we can update them all to 2020 (currently are all at 2017) and add `Copyright 2021 Python Language Server Contributors` in addition to the old Palantir notices, which would be unambiguous (#10)

**Comment by ccordoba12** [comment]
> rewrite the readme to markdown

Agreed.

> remove Python 2 support

I think we shouldn't mix renaming the package and getting it off the ground with this task. So for now we should just make sure everything is working fine after the rename.

> update copyrights notices

Agreed.

**Comment by frenzymadness** [comment]
If I might add a point: It would be nice to add Python 3.9 and 3.10 (alpha 6 currently) to the CI.

**Comment by krassowski** [comment]
Note on PyPI package: python-ls is already taken (https://pypi.org/project/python-ls/) and does not seem as a good target for PEP 541 procedure (as it has some users and was active within last 2 years); it might be easier to reclaim pyls using PEP 541 (which would need to be reported here https://github.com/pypa/pypi-support/issues and seem to take a long time anyways). Probably another (temporary?) name might be needed.

**Comment by ccordoba12** [comment]
> Probably another (temporary?) name might be needed.

Yeah, I agree with that. What about `pyls-server`?

**Comment by xrogaan** [comment]
If you have trouble finding a proper name, I would suggest *yet another python-language-server*, or *yapls* for short. (And it rolls off the tongue!) *apls* is sadly already taken.

**Comment by bnavigator** [comment]
*yap**y**ls*

Turkish yapılış: https://translate.google.com/?sl=tr&tl=en&text=yapilis&op=translate

**Comment by bnavigator** [comment]
Any news? With Python 3.9 the pressure increases to update Jedi from 0.17.2. pyls is one of the show stoppers to do so.

**Comment by ccordoba12** [comment]
We will put resources to make this transition a reality most probably during April. But we can't commit to do it before that time.

**Comment by xiaoxiae** [comment]
Other names (taken from "Python Language Server") that sound decent are `PLanS` and `PyLaSer`.

**Comment by marimeireles** [comment]
PyLaSer is really cool.
Also, hope I can help around a bit! :)

**Comment by marimeireles** [comment]
> Note on PyPI package: python-ls is already taken (https://pypi.org/project/python-ls/) and does not seem as a good target for PEP 541 procedure (as it has some users and was active within last 2 years); it might be easier to reclaim pyls using PEP 541 (which would need to be reported here https://github.com/pypa/pypi-support/issues and seem to take a long time anyways). Probably another (temporary?) name might be needed.

Hey @krassowski :)
I didn't find an issue there, do you mind if I open one?
Also, how can I help with the pypi release? Should we complete this list first?

**Comment by ccordoba12** [comment]
Hey @marimeireles, @andfoy is working on that in PR #10.

**Comment by douglasdavis** [comment]
After https://github.com/python-lsp/python-lsp-server/pull/10 is the "official" new name for the executable `pylsp`? (asking to help transition https://github.com/emacs-lsp/lsp-mode/)

**Comment by ccordoba12** [comment]
The name of the module, you mean?

**Comment by douglasdavis** [comment]
I mean the entry point in `setup.py`:
https://github.com/python-lsp/python-lsp-server/blob/0a3352d4737f935a3f486229bb1d0a93d3471db8/setup.py#L72

**Comment by ccordoba12** [comment]
Yep, that's the new name.

**Comment by andfoy** [comment]
We have our first release officially on PyPI! https://pypi.org/project/python-lsp-server/, thanks for your help with the transition

**Comment by bnavigator** [comment]
What's next? Migrate spyder and all the plugins?

**Comment by andfoy** [comment]
Yes, also we need to publish new conda-forge packages, as well opening issues in all known pyls plugins to inform their maintainers that they should update to use the new package
